[project]
name = "crms"
version = "1.0.0"
description = "Car Rental Management System"
requires-python = ">=3.12"
dependencies = [
    "Flask==3.0.3",
    "Flask-Migrate==4.0.7",
    "Flask-SQLAlchemy==3.1.1",
    "SQLAlchemy==2.0.36",
    "gunicorn==23.0.0",
    "psycopg2-binary==2.9.9",
    "python-dotenv==1.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.3",
]

[tool.vercel]
entrypoint = "wsgi:app"