"""Add actual pickup datetime to bookings

Revision ID: 2f21d2fa0169
Revises: 4d1ab4d1f06d
Create Date: 2026-09-19 19:04:09.824089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f21d2fa0169'
down_revision = '4d1ab4d1f06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_pickup_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('actual_pickup_datetime')

    # ### end Alembic commands ###
